service: ssrserverless-angular-app

plugins:
  - serverless-apigw-binary

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 128
  timeout: 30
  stage: staging
  region: ap-south-1
  lambdaHashingVersion: 20201221

package:
  exclude:
   - src/**
   - node_modules/**
   - e2e/**
   - coverage/**
   - 'node_modules/@vendia/serverless-express/**'
   ##- '!src/assets/**'
   - '!node_modules/aws-serverless-express/**'
   - '!node_modules/binary-case/**'
   - '!node_modules/type-is/**'
   - '!node_modules/media-typer/**'
   - '!node_modules/mime-types/**'
   - '!node_modules/mime-db/**'
   

custom:
  apigwBinary:
    types:
      - '*/*'

functions:
  api:
    handler: lambda.ssrserverless
    events:
      - http: ANY {proxy+}
      - http: ANY /